const https = require('https');

const TELEGRAM_TOKEN = process.env.TELEGRAM_TOKEN || '8696337871:AAH26fVQUToNVoVkp1c1mwEFwB_cqq31FJc';
const TELEGRAM_CHAT_ID = process.env.TELEGRAM_CHAT_ID || '1234567890';
const DEXSCREENER_API = 'https://api.dexscreener.com/latest/dex/tokens';

const ALERT_CONFIG = {
  volumeThreshold: 100,
    holderThreshold: 30,
      minAge: 30,
        maxRiskScore: 70,
        };

        const recentAlerts = new Set();

        function calculateRiskScore(coin) {
          let score = 0;
            if (coin.priceChange24h > 200) score += 30;
              else if (coin.priceChange24h > 100) score += 20;
                if (coin.holderConcentration > 40) score += 25;
                  else if (coin.holderConcentration > 25) score += 15;
                    if (coin.ageDays < 7) score += 25;
                      else if (coin.ageDays < 30) score += 15;
                        if (coin.holders < 5000) score += 15;
                          else if (coin.holders < 10000) score += 8;
                            if (coin.volumeLiquidityRatio > 10) score += 10;
                              return Math.min(score, 100);
                              }

                              function getRiskLevel(score) {
                                if (score > 70) return { emoji: '🔴', text: 'VERY HIGH' };
                                  if (score > 50) return { emoji: '🟠', text: 'HIGH' };
                                    if (score > 30) return { emoji: '🟡', text: 'MEDIUM' };
                                      return { emoji: '🟢', text: 'LOW' };
                                      }

                                      function formatNumber(num) {
                                        if (num >= 1000000) return (num / 1000000).toFixed(1) + 'M';
                                          if (num >= 1000) return (num / 1000).toFixed(1) + 'K';
                                            return num.toFixed(2);
                                            }

                                            function sendTelegramMessage(text, buttons = null) {
                                              return new Promise((resolve, reject) => {
                                                  const payload = {
                                                        chat_id: TELEGRAM_CHAT_ID,
                                                              text: text,
                                                                    parse_mode: 'HTML',
                                                                          disable_web_page_preview: true,
                                                                              };
                                                                                  if (buttons) {
                                                                                        payload.reply_markup = { inline_keyboard: buttons };
                                                                                            }
                                                                                                const postData = JSON.stringify(payload);
                                                                                                    const options = {
                                                                                                          hostname: 'api.telegram.org',
                                                                                                                port: 443,
                                                                                                                      path: `/bot${TELEGRAM_TOKEN}/sendMessage`,
                                                                                                                            method: 'POST',
                                                                                                                                  headers: {
                                                                                                                                          'Content-Type': 'application/json',
                                                                                                                                                  'Content-Length': Buffer.byteLength(postData),
                                                                                                                                                        },
                                                                                                                                                            };
                                                                                                                                                                const req = https.request(options, (res) => {
                                                                                                                                                                      let data = '';
                                                                                                                                                                            res.on('data', (chunk) => (data += chunk));
                                                                                                                                                                                  res.on('end', () => {
                                                                                                                                                                                          try {
                                                                                                                                                                                                    const response = JSON.parse(data);
                                                                                                                                                                                                              resolve(response);
                                                                                                                                                                                                                      } catch (e) {
                                                                                                                                                                                                                                reject(e);
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                      req.on('error', reject);
                                                                                                                                                                                                                                                          req.write(postData);
                                                                                                                                                                                                                                                              req.end();
                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                function fetchDexscreenerData(tokenAddresses) {
                                                                                                                                                                                                                                                                  return new Promise((resolve) => {
                                                                                                                                                                                                                                                                      const mockData = [
                                                                                                                                                                                                                                                                            { symbol: 'DOGGO', address: 'sol_doggo_123', price: 0.00034, priceChange24h: 156, volume24h: 234000, liquidity: 45000, holders: 8900, holderConcentration: 35, ageDays: 12 },
                                                                                                                                                                                                                                                                                  { symbol: 'BOME', address: 'sol_bome_456', price: 0.0089, priceChange24h: 42, volume24h: 8900000, liquidity: 1200000, holders: 32000, holderConcentration: 8, ageDays: 234 },
                                                                                                                                                                                                                                                                                        { symbol: 'FLOKI', address: 'sol_floki_789', price: 0.00018, priceChange24h: 34, volume24h: 3400000, liquidity: 890000, holders: 45000, holderConcentration: 6, ageDays: 600 },
                                                                                                                                                                                                                                                                                            ];
                                                                                                                                                                                                                                                                                                resolve(mockData);
                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                  async function monitorMemecoin() {
                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                        const coins = await fetchDexscreenerData(['sol_doggo_123', 'sol_bome_456', 'sol_floki_789']);
                                                                                                                                                                                                                                                                                                            for (const coin of coins) {
                                                                                                                                                                                                                                                                                                                  const volumeLiquidityRatio = coin.volume24h / coin.liquidity;
                                                                                                                                                                                                                                                                                                                        coin.volumeLiquidityRatio = volumeLiquidityRatio;
                                                                                                                                                                                                                                                                                                                              const riskScore = calculateRiskScore(coin);
                                                                                                                                                                                                                                                                                                                                    const riskLevel = getRiskLevel(riskScore);
                                                                                                                                                                                                                                                                                                                                          const isPump = coin.priceChange24h > ALERT_CONFIG.volumeThreshold;
                                                                                                                                                                                                                                                                                                                                                const isAcceptableRisk = riskScore <= ALERT_CONFIG.maxRiskScore;
                                                                                                                                                                                                                                                                                                                                                      const notAlreadySent = !recentAlerts.has(coin.symbol);
                                                                                                                                                                                                                                                                                                                                                            if (isPump && isAcceptableRisk && notAlreadySent) {
                                                                                                                                                                                                                                                                                                                                                                    const jupiterLink = `https://jup.ag/swap/SOL-${coin.address}?amount=1000000&slippageBps=500`;
                                                                                                                                                                                                                                                                                                                                                                            const message = `🚀 <b>PUMP DETECTED</b>\n\n<b>${coin.symbol}</b>\n💰 Price: $${coin.price.toExponential(2)}\n📈 Change 24h: <b>${coin.priceChange24h.toFixed(1)}%</b>\n💵 Volume: $${formatNumber(coin.volume24h)}\n👥 Holders: ${formatNumber(coin.holders)}\n\n<b>Risk Analysis:</b>\n${riskLevel.emoji} Risk Score: <b>${riskScore}/100</b>\n⚠️ Top Holder: ${coin.holderConcentration}%\n📅 Age: ${coin.ageDays} giorni\n💧 Liquidity: $${formatNumber(coin.liquidity)}\n\n<i>${riskLevel.text}</i>`;
                                                                                                                                                                                                                                                                                                                                                                                    const buttons = [[ { text: '📊 Chart', url: `https://dexscreener.com/solana/${coin.address}` }, { text: '🔗 Jupiter', url: jupiterLink } ], [ { text: '❌ Ignora', callback_data: `ignore_${coin.symbol}` } ]];
                                                                                                                                                                                                                                                                                                                                                                                            await sendTelegramMessage(message, buttons);
                                                                                                                                                                                                                                                                                                                                                                                                    recentAlerts.add(coin.symbol);
                                                                                                                                                                                                                                                                                                                                                                                                            setTimeout(() => recentAlerts.delete(coin.symbol), 2 * 60 * 60 * 1000);
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                            console.error('Monitor error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                await sendTelegramMessage(`❌ Monitor error: ${error.message}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log('🤖 Memecoin Bot avviato...');
                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log(`Chat ID: ${TELEGRAM_CHAT_ID}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log(`Monitoring ogni 30 secondi...\n`);
                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                  monitorMemecoin();
                                                                                                                                                                                                                                                                                                                                                                                                                                  setInterval(monitorMemecoin, 30000);
                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log('✓ Bot in ascolto...');
